### PR TITLE
Modifications to the deployment and the mail templates

### PR DESCRIPTION
**Pull request by ayopedro**

### CODE REVIEW

**Comment by tobisupreme** [comment]
Please in the future, these changes should come in different PRs as they are unrelated changes

**Comment by tobisupreme** [comment]
They should also come in their branches. These things aren't giving "scheduler"

**Comment by ayopedro** [comment]
> They should also come in their branches. These things aren't giving "scheduler"

was just a quick fix. should have switched branches

**Review by tobisupreme — APPROVED** [review]

**Comment by tobisupreme** [comment]
> > They should also come in their branches. These things aren't giving "scheduler"
> 
> was just a quick fix. should have switched branches

yinmu

**Review by enosefelix — APPROVED** [review]

**Pull request merged**
